### ISSUE TITLE
Standarize problem output

### ISSUE THREAD

**Issue by WildCard65** [alliedmodders/ambuild#122]
Would it be possible to implement a way to convert compiler specific problem output into a generic problem output?

This would allow for better integration into Visual Studio Code where you can define custom problem matchers, reference: [Visual Studio Code: Tasks: Custom Problem Matcher](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher)

**Comment by dvander** [comment]
AMBuild relays exactly what the compiler sends to stderr/stdout. Is VSCode's pattern matching not working because of something else AMBuild is doing?

**Comment by WildCard65** [comment]
I was more asking for the GH action I created as I want to implement annotations in it without wasting CPU cycles testing the stderr output against 2 different regex patterns.
