### ISSUE TITLE
How to change to vs ?   i wanna debug project

### ISSUE THREAD

**Issue by YuanBaian** [alliedmodders/ambuild#126]

**Comment by SlidyBat** [comment]
You can generate a VS project by specifying the `--gen` param when running `configure.py`. You can also use `--vs-version` to specify which version of VS you want to generate a project for.

Example command:
`python ../configure.py --gen vs --vs-version 2019`

You may come across a couple of issues though (e.g. #53, #54), support for this feature isn't the best.
