### ISSUE TITLE
test-c.exe and test-cxx.exe detected as trojans

### ISSUE THREAD

**Issue by gravitydeepimpactsun** [alliedmodders/ambuild#154]
While trying to run configure.py Kaspersky flagged test-c.exe as VHO:Trojan.Win32.Convagent.gen

https://www.virustotal.com/gui/file/7d765ec6f4771f4427bc05cea58b7058908c699735666ab245b5194e7d3d7bb9?nocache=1
https://www.virustotal.com/gui/file/684321975e7a5498fb45f635ac3ad68ac8fd3f1e4da43defb7228e7aaeac9b47?nocache=1

**Comment by psychonic** [comment]
It's a false positive. You would have to report it to the Antivirus vendor.
