### ISSUE TITLE
how to make a dll without any source file only .rc file

### ISSUE THREAD

**Issue by LittleKu** [alliedmodders/ambuild#58]
As the title, when I create a build script for a project that only has a resource file, and my script is 
```
binary = cfg.Library(builder, 'project_name', builder.target.arch)
compiler = binary.compiler
compiler.linkflags += [
    '/NOENTRY',
]
compiler.includes += [
    os.path.join(builder.currentSourcePath),
]

binary.sources += [
    'project_resource.rc',
]

builder.Add(binary)
```

and it will tell me the error, but the dll file will be generated, the error message will like this : 
`Expected output file, but not found: project.exp`

how to do it correctly

**Comment by dvander** [comment]
Thanks, I know this is late, but this turned out to be a very simple bug (and in fact the code had a comment predicting that it'd be broken in some edge case - this turned out to be the edge case).

Anyway this use case is now supported.
