### ISSUE TITLE
[windows] how to get lib name

### ISSUE THREAD

**Issue by LittleKu** [alliedmodders/ambuild#59]
It seem that couldn't get lib name. For example, a Library(**Not StaticLibrary**), I want to get the *.lib name,  but I can't get it, only two attribute "binary"(*.exe, *.lib, *.dll) and "debug"(debug symbol)

**Comment by dvander** [comment]
Sorry for not seeing this sooner, but for posterity: the library name is available in the final binary node. Eg:

```
task = builder.Add(library)
print(task.binary.path)
```

This should give you the path, and you can os.path.split() it to get the name.
