### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by WildCard65** [alliedmodders/ambuild#72]
At this point in time, Python 2's life is very much over in favour of Python 3, AMBuild should be upgraded to drop Python 2 support some time soon, allowing for better performance overall.

Should Python 2 support still be required further though, a stop-gap solution will be relying on the 'six' module, as it's a Python 2/3 support library. Ultimately though, Python 2 should be dropped.

On the flip side, Python 3 introduced new libraries that AMBuild can take full advantage of, one of them is name 'pathlib', a platform independent-ish package for handling path/pathlike objects. A new interface was also introduced called 'os.PathLike' and most Python methods now accept string/PathLike objects.

**Comment by dvander** [comment]
Python 2 support costs almost nothing to maintain, we've factored it mostly into one file, and AMBuild gets very little maintenance to begin with. There are lots of legacy systems out there that will have Python 2 for a long time. All of our infrastructure uses Python 2, so there's some janitorial work that'd need to precede this. So, those are reasons not to bother. Let's take a look at the benefits...

My initial glance of pathlib is that it does not look very useful. The ability to construct and decode paths is not a pressing issue, and is one already solved by basic operators. Certainly, it's not big enough of a problem to justify a massive refactoring.

I do see that Python 3 has `multiprocessing.connection.wait`, which seems like it would allow me to replace the train wreck IPC layer AMBuild has. That layer is a huge maintenance burden with known bugs. It's possible that Python's IPC implementation is less buggy.

Even that though is pretty minor.

**Comment by WildCard65** [comment]
@dvander Welp, this issue and #68 are going to be linked if we have to switch to using 'pip' to install AMBuild, pip is warning that support for Python 2 will eventually be dropped.
