### ISSUE TITLE
AMBuild V2.2 idea: Proper package versioning.

### ISSUE THREAD

**Issue by WildCard65** [alliedmodders/ambuild#82]
Currently AMBuild has a problem with versioning itself with the installer, setuptools and by extension pip sees it as version 2.0.

For 2.2, we should start better marking the version so upgrades won't require the "--force" argument.

There is an extension called setuptools-git-versioning that uses ```git describe``` to obtain version info. This will also allow users to pin an AMBuild version to a specific API version.

Also: @dvander can you create an API 2.2 milestone?

**Comment by dvander** [comment]
I'll start the 2.2 API sometime this week. I agree it would be nice to have the package version match the latest available API version. If you know a good way to do this, feel free to submit a PR.

**Comment by WildCard65** [comment]
How about [setuptools-git-versioning](https://pypi.org/project/setuptools-git-versioning/)?

It's automaticly sets the package version via git tags, we can also customize the result (up to an extent)

**Comment by dvander** [comment]
Sure, no objections. As long as it can deduce the correct version from master.

**Comment by WildCard65** [comment]
It uses git tags via ```git describe```, most tools that do the same auto versioning also uses that command.

It may get confused with the current tag you created so we may need a plain "v2.1" tag.

**Comment by dvander** [comment]
I've retcon'd some tags into place.
